<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Переключить отображение с абс на проценты</name>
   <tag></tag>
   <elementGuidId>eefc6eb0-af99-4fd5-97bf-5e82a13d55a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='43086f266455497c8d491ba5cbfbc368']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#43086f266455497c8d491ba5cbfbc368 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bd411986-3bfa-4522-90df-559ad6984350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;43086f266455497c8d491ba5cbfbc368&quot;)/div[1]</value>
      <webElementGuid>c5190e76-3f4f-42f8-a2b8-ba809b38bde1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='43086f266455497c8d491ba5cbfbc368']/div</value>
      <webElementGuid>0a8edd83-f24c-40b2-9bba-d9e90790249e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div[2]/div/div</value>
      <webElementGuid>88520fe4-164c-4d68-89d8-837d4faf3d4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
